# Generated by Django 6.0.6 on 2026-07-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Critical', 'Critical'), ('Notice', 'Notice')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('donor_type', models.CharField(choices=[('Blood', 'Blood'), ('Organ', 'Organ'), ('Blood + Organ', 'Blood + Organ')], max_length=30)),
                ('blood_type', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=5)),
                ('region', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('organs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Contacted', 'Contacted'), ('Medical Review', 'Medical Review')], default='Available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=5, unique=True)),
                ('units', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RecipientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('need_type', models.CharField(choices=[('Blood', 'Blood'), ('Organ', 'Organ')], max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Standard', 'Standard')], max_length=20)),
                ('blood_type', models.CharField(max_length=5)),
                ('organ', models.CharField(blank=True, max_length=50)),
                ('hospital', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('site', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='donation.donor')),
            ],
        ),
    ]
